ALTER TABLE kyc_application
    ADD COLUMN IF NOT EXISTS verification_methods_csv VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS verification_provider VARCHAR(120),
    ADD COLUMN IF NOT EXISTS verification_reference VARCHAR(120),
    ADD COLUMN IF NOT EXISTS verification_summary_text TEXT,
    ADD COLUMN IF NOT EXISTS verification_reference_ids_csv VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS aadhaar_number_masked VARCHAR(32),
    ADD COLUMN IF NOT EXISTS aadhaar_basic_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS aadhaar_ocr_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS driving_license_masked VARCHAR(32),
    ADD COLUMN IF NOT EXISTS driving_license_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS passport_masked VARCHAR(32),
    ADD COLUMN IF NOT EXISTS passport_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS voter_id_masked VARCHAR(32),
    ADD COLUMN IF NOT EXISTS voter_id_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS face_match_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS face_liveness_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS selfie_image_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS id_document_image_url VARCHAR(500);
